version: "2"
networks:
  default:
    external:
      name: blitzkrieg-default-network
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD=trust

    volumes:
      - flask-app-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  usermgmt:
    container_name: user-management
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: thertion12/user-management
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 6000:6000

    depends_on:
      - postgres

volumes:
  flask-app-db:
