version: "2"
networks:
  default:
    external:
      name: blitzkrieg-default-network
services:
  postgres:
    container_name: postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-postgres
    image: thertion12/postgres
    volumes:
      - flask-app-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  usermgmt:
    container_name: user-management
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: thertion12/user-management
    env_file:
      - .env
    ports:
      - 6000:6000

    depends_on:
      - postgres

volumes:
  flask-app-db:
