version: "2"
networks:
    default:
      external:
        name: blitzkrieg-default-network
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:5.3.1
        container_name: zookeeper
        hostname: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181

    kafka:
        image: confluentinc/cp-kafka:5.3.1
        container_name: kafka
        hostname: kafka
        ports:
            - "9092:9092"
        restart: always
        
        environment:
            KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
            KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
            KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
            KAFKA_BROKER_ID: 1
            KAFKA_LOG4J_LOGGERS: ${KAFKA_LOG4J_LOGGERS}
            KAFKA_DEFAULT_REPLICATION_FACTOR: 1
            KAFKA_NUM_PARTITIONS: 3
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
            - zookeeper
