version: "2"
networks:
    default:
      external:
        name: blitzkrieg-default-network
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:5.3.1
        container_name: zookeeper
        hostname: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181

    kafka:
        image: confluentinc/cp-kafka:5.3.1
        container_name: kafka
        hostname: kafka
        ports:
            - "9092:9092"
        restart: always
        env_file:
            - .env    
        depends_on:
            - zookeeper
