kind: Service
apiVersion: v1
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app:  api-gateway
  ports:
  - name: http-server
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30038
  - name: http-port
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30031