kind: Service
apiVersion: v1
metadata:
  name: ui-service
spec:
  type: NodePort
  selector:
    app: ui-service
  ports:
  - name: http-server
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30037

