version: "3.7"
networks:
  default:
    external:
      name: blitzkrieg-default-network
services:
  session:
    container_name: session-management
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    image: thertion12/session-management
    ports:
      - "8084:8084"
