version: "3.7"
networks:
    default:
      external:
        name: blitzkrieg-default-network
services:
    ui:
        container_name: user-interface
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        image: user-interface:1.0
        ports:
            - "3000:3000"
        