version: "2"
networks:
    default:
      external:
        name: blitzkrieg-default-network
services:
    ui:
        container_name: user-interface
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        image: thertion12/user-interface
        ports:
            - "3000:3000"
        
